import { useMemo } from 'react';
import { createGlobalStore, getGlobalStore, useStore } from '@openmrs/esm-framework';

/**
 * The clinical acuity of a notification. This mirrors the "Acuity level?" decision
 * in the smart notification workflow: `routine` events update the chart silently
 * while `critical` and `stat` events increment the bell badge.
 */
export type NotificationAcuity = 'routine' | 'critical' | 'stat';

/**
 * A single smart notification generated by a clinical event (a lab result,
 * a medication alert, an observation, etc.).
 */
export interface SmartNotification {
  /** A stable, unique identifier for the notification. */
  id: string;
  /** A short, human-readable summary of the event. */
  title: string;
  /** The detail body shown when the notification is expanded. */
  message: string;
  /** The clinical acuity used for badge counting and priority sorting. */
  acuity: NotificationAcuity;
  /** The source of the event, e.g. "Lab result", "Medication alert", "Observation". */
  category: string;
  /** The patient the notification relates to, used to link to the chart. */
  patientUuid?: string;
  /** The display name of the patient. */
  patientName?: string;
  /** The location where the event originated, e.g. a ward or bed. */
  location?: string;
  /** The time the event fired, as an ISO-8601 string. */
  createdAt: string;
  /** Whether the notification has been read (reviewed) by a clinician. */
  read: boolean;
  /** The display name of the reviewer, populated when the notification is reviewed. */
  reviewedBy?: string;
  /** The time the notification was reviewed, as an ISO-8601 string. */
  reviewedAt?: string;
}

export interface NotificationsStore {
  notifications: Array<SmartNotification>;
}

export const notificationsStoreName = 'smart-notifications';

/** The order in which acuities are shown in the panel (highest priority first). */
const acuityRank: Record<NotificationAcuity, number> = {
  stat: 0,
  critical: 1,
  routine: 2,
};

const initialState: NotificationsStore = {
  notifications: getSeedNotifications(),
};

export const notificationsStore = createGlobalStore<NotificationsStore>(notificationsStoreName, initialState);

/**
 * Returns the shared notifications store. Other frontend modules (or a backend
 * event listener) can use this to push new notifications into the bell.
 */
export function getNotificationsStore() {
  return getGlobalStore<NotificationsStore>(notificationsStoreName, initialState);
}

/**
 * Adds a new notification to the top of the inbox. This is the public entry point
 * used when a clinical event is fired and classified.
 */
export function addNotification(notification: Omit<SmartNotification, 'read'> & { read?: boolean }): void {
  const store = getNotificationsStore();
  const { notifications } = store.getState();
  if (notifications.some((existing) => existing.id === notification.id)) {
    return;
  }
  store.setState({
    notifications: [{ read: false, ...notification }, ...notifications],
  });
}

/**
 * Marks a notification as reviewed, persisting the reviewer and timestamp. This
 * decrements the unread badge, matching the "Mark reviewed" branch of the workflow.
 */
export function markNotificationReviewed(id: string, reviewedBy: string): void {
  const store = getNotificationsStore();
  const now = new Date().toISOString();
  store.setState((state) => ({
    notifications: state.notifications.map((notification) =>
      notification.id === id && !notification.read
        ? { ...notification, read: true, reviewedBy, reviewedAt: now }
        : notification,
    ),
  }));
}

/** Marks every unread notification as reviewed. */
export function markAllNotificationsReviewed(reviewedBy: string): void {
  const store = getNotificationsStore();
  const now = new Date().toISOString();
  store.setState((state) => ({
    notifications: state.notifications.map((notification) =>
      notification.read ? notification : { ...notification, read: true, reviewedBy, reviewedAt: now },
    ),
  }));
}

/** Returns true when the acuity should contribute to the bell badge count. */
export function isBadgeAcuity(acuity: NotificationAcuity, countRoutine: boolean): boolean {
  return countRoutine || acuity === 'critical' || acuity === 'stat';
}

/** Sorts notifications by acuity (highest first) then by recency. */
export function sortNotifications(notifications: Array<SmartNotification>): Array<SmartNotification> {
  return [...notifications].sort((a, b) => {
    if (acuityRank[a.acuity] !== acuityRank[b.acuity]) {
      return acuityRank[a.acuity] - acuityRank[b.acuity];
    }
    return new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime();
  });
}

/**
 * React hook exposing the sorted notifications and the unread badge count.
 *
 * @param countRoutine whether routine notifications count towards the badge.
 */
export function useNotifications(countRoutine: boolean) {
  // `useStore` spreads the selected state into a new object, so we select the whole
  // store (which preserves the `notifications` array) rather than the array directly.
  const { notifications } = useStore(notificationsStore);

  return useMemo(() => {
    const sorted = sortNotifications(notifications);
    const unreadCount = sorted.filter((n) => !n.read && isBadgeAcuity(n.acuity, countRoutine)).length;
    return { notifications: sorted, unreadCount };
  }, [notifications, countRoutine]);
}

/**
 * Seed data so the bell is demonstrable without a backend. A real deployment would
 * clear these and push notifications via {@link addNotification} from a backend
 * event listener.
 */
function getSeedNotifications(): Array<SmartNotification> {
  const now = Date.now();
  const minutesAgo = (minutes: number) => new Date(now - minutes * 60_000).toISOString();

  return [
    {
      id: 'seed-critical-potassium',
      title: 'Critical potassium result',
      message: 'Serum potassium 6.8 mmol/L (critical high). Immediate review required.',
      acuity: 'stat',
      category: 'Lab result',
      patientName: 'John Amos',
      location: '209 - Group 1 Ward, Bed 4',
      createdAt: minutesAgo(3),
      read: false,
    },
    {
      id: 'seed-critical-allergy',
      title: 'Medication allergy alert',
      message: 'Ordered amoxicillin conflicts with a documented penicillin allergy.',
      acuity: 'critical',
      category: 'Medication alert',
      patientName: 'Mary Chelimo',
      location: '209 - Group 1 Ward, Bed 12',
      createdAt: minutesAgo(18),
      read: false,
    },
    {
      id: 'seed-critical-vitals',
      title: 'Abnormal vital signs',
      message: 'Recorded SpO2 88% on room air. Escalation recommended.',
      acuity: 'critical',
      category: 'Observation',
      patientName: 'Peter Odhiambo',
      location: '209 - Group 1 Ward, Bed 7',
      createdAt: minutesAgo(42),
      read: false,
    },
    {
      id: 'seed-routine-hematology',
      title: 'Routine hematology result available',
      message: 'Full blood count results are ready for review.',
      acuity: 'routine',
      category: 'Lab result',
      patientName: 'Grace Wanjiru',
      location: '209 - Group 1 Ward, Bed 2',
      createdAt: minutesAgo(75),
      read: false,
    },
  ];
}
